services:
  - type: web
    name: mab-api
    runtime: docker
    dockerfilePath: ./bandit_api/Dockerfile
    dockerContext: .
    plan: free
    region: ohio
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        sync: false
      - key: ACTIVE_STRATEGY
        value: THOMPSON
      - key: LOG_LEVEL
        value: INFO
